on: 
  workflow_dispatch:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main

jobs: 
  check-install:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: install package
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: install test dependencies
        run: |
          pip install -r requirements-dev.txt

      - name: run tests
        run: |
          pytest
      